FROM golang:1.16-alpine AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/app cmd/main.go

FROM golang:1.16-alpine
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait && apk add  --no-cache ffmpeg
COPY --from=build /bin/app /bin/app
CMD /wait && /bin/app
