version: '3.1'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        env_file: .env
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    postgresql:
        image: postgres:13-alpine 
        container_name: postgresql
        env_file: .env
        restart: always
        hostname: "postgres.local"
        ports:
            - "5432:5432" 
        volumes:
            - postgresql:/var/lib/postgresql/data 
            - ./scripts/docker-schema.sql:/docker-entrypoint-initdb.d/0_init.sql
    audio-converter:
        build:
            context: ./
        container_name: audio-converter
        env_file: .env
        restart: always
        hostname: "converter.local"
        environment:
            WAIT_HOSTS: postgresql:5432
        ports:
            - "8000:8000"
        depends_on: [postgresql]

volumes:
    postgresql:
        driver: local
