version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "converter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ws48mo7s36yw"
s3_prefix = "converter"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
