AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam
  
  Sample SAM Template for sam

Globals:
  Function:
    Timeout: 10
    Runtime: go1.x
    Environment:
      Variables:
        REMOTE_HOST: REMOTE_HOST
        POSTGRES_PORT: POSTGRES_PORT
        POSTGRES_USER: POSTGRES_USER
        POSTGRES_PASSWORD: POSTGRES_PASSWORD
        POSTGRES_DB: POSTGRES_DB
        SSLMODE: SSLMODE
        PRIVATEKEY: PRIVATEKEY
        PUBLICKEY: PUBLICKEY
        AWS_BUCKET: AWS_BUCKET

Resources:
  AudioConverterFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: cmd/
      Handler: cmd
      Tracing: Active
      Events:
        SignUp:
          Type: Api 
          Properties:
            Path: /signup
            Method: POST
        LogIn: 
          Type: Api 
          Properties:
            Path: /login
            Method: POST
        Docs: 
          Type: Api 
          Properties:
            Path: /docs
            Method: GET    
        Conversion: 
          Type: Api 
          Properties:
            Path: /conversion
            Method: POST    
        History: 
          Type: Api 
          Properties:
            Path: /request_history
            Method: GET  
        Download: 
          Type: Api 
          Properties:
            Path: /download_audio/{id}
            Method: GET  
    