---

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15.8
        auth:
          username: katiasuya
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6-alpine
        auth:
          username: katiasuya
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: audioconverter 
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    parallelism: 2

    environment: 
      TEST_RESULTS: /tmp/test-results      
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS 
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m       
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /home/circleci/go/pkg/mod
      - run:
          name: Run tests
          command: go test ./...
      - run:
          name: Start service
          command: go run cmd/main.go
          background: true 
      - run:
          name: Validate service is working
          command: |
            sleep 5
            curl --retry 10 --retry-delay 1 -X POST --header "Content-Type: application/json" -d '{"username":"TestUser", "password": "qwerty123"}' http://localhost:8000/user/signup
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2.1
  build-workflow: 
    jobs: 
      - build

...
