---

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15.8
        auth:
          username: katiasuya
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6-alpine
        auth:
          username: katiasuya
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: audioconverter 
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_HOST_AUTH_METHOD: trust

    parallelism: 2

    environment: 
      TEST_RESULTS: /tmp/test-results      
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS 
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m       
      - save_cache:
          key: v1-pkg-cache
          paths:
            - ~/.cache/go-build
      - run:
          name: Run tests
          command: go test -v ./...
      - run:
          name: Start service
          environment:
            CONTACTS_DB_URL: "postgres://postgres@localhost:5432/audioconverter?sslmode=disable"
          command: ./workdir/user/signup
          background: true 
      - run:
          name: Validate service is working
          command: |
            sleep 5
            curl --retry 10 --retry-delay 1 -X POST --header "Content-Type: application/json" -d '{username":"Test User", "password": "qwerty123"}' http://localhost:8000/user/signup
      - store_test_results:
          path: /tmp/test-reports
workflows:
  version: 2.1
  build-workflow: 
    jobs: 
      - build

...
